// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Arangodb from "./database/Arangodb.mjs";

var Arangodb$1;

var make = Arangodb.make;

var createArangoDBService = Arangodb.createArangoDBService;

var initialize = Arangodb.initialize;

var getSiteByUrl = Arangodb.getSiteByUrl;

var getRecentScansForSite = Arangodb.getRecentScansForSite;

var getViolationsForScan = Arangodb.getViolationsForScan;

var getTopSites = Arangodb.getTopSites;

var getCommonViolations = Arangodb.getCommonViolations;

var getSiteViolationTrend = Arangodb.getSiteViolationTrend;

var getOrganizationSites = Arangodb.getOrganizationSites;

export {
  Arangodb$1 as Arangodb,
  make ,
  createArangoDBService ,
  initialize ,
  getSiteByUrl ,
  getRecentScansForSite ,
  getViolationsForScan ,
  getTopSites ,
  getCommonViolations ,
  getSiteViolationTrend ,
  getOrganizationSites ,
}
/* Arangodb Not a pure module */
