// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Scanner from "./Scanner.mjs";

var Scanner$1;

var make = Scanner.make;

var createScanner = Scanner.createScanner;

export {
  Scanner$1 as Scanner,
  make ,
  createScanner ,
}
/* Scanner Not a pure module */
