// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

var Puppeteer = {};

var Playwright = {};

var Fs$1 = {};

function make() {
  var path = require.resolve("axe-core/axe.min.js");
  return {
          axeSource: Fs.readFileSync(path, "utf8")
        };
}

function calculateScore(_axeResults) {
  return PervasivesU.failwith("TODO: calculateScore not yet implemented");
}

async function scanWithPuppeteer(_self, _options, _startTime) {
  return PervasivesU.failwith("TODO: scanWithPuppeteer not yet implemented");
}

async function scan(self, options) {
  var startTime = Date.now();
  var engine = Core__Option.getOr(options.engine, "puppeteer");
  if (engine === "playwright") {
    return PervasivesU.failwith("TODO: scanWithPlaywright not yet implemented");
  } else {
    return await scanWithPuppeteer(self, options, startTime);
  }
}

var createScanner = make;

export {
  Puppeteer ,
  Playwright ,
  Fs$1 as Fs,
  make ,
  calculateScore ,
  scanWithPuppeteer ,
  scan ,
  createScanner ,
}
/* fs Not a pure module */
