# SPDX-License-Identifier: MPL-2.0

[project]
name = "accessibility-everywhere"
description = "Accessibility Everywhere"

[container]
base = "cgr.dev/chainguard/wolfi-base:latest"

[build]
builder = "deno"
