// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function variantClass(v) {
  if (v === "primary") {
    return "a11y-button--primary";
  } else if (v === "ghost") {
    return "a11y-button--ghost";
  } else if (v === "danger") {
    return "a11y-button--danger";
  } else {
    return "a11y-button--secondary";
  }
}

function sizeClass(s) {
  if (s === "md") {
    return "a11y-button--md";
  } else if (s === "sm") {
    return "a11y-button--sm";
  } else {
    return "a11y-button--lg";
  }
}

var make = React.forwardRef(function (props, ref) {
      var variant = Core__Option.getOr(props.variant, "primary");
      var size = Core__Option.getOr(props.size, "md");
      var loading = Core__Option.getOr(props.loading, false);
      var disabled = Core__Option.getOr(props.disabled, false);
      var className = Core__Option.getOr(props.className, "");
      var type_ = Core__Option.getOr(props.type, "button");
      var busy = disabled || loading;
      var classes = [
            "a11y-button",
            variantClass(variant),
            sizeClass(size),
            loading ? "a11y-button--loading" : "",
            className
          ].filter(function (s) {
              return s !== "";
            }).join(" ");
      var domRef = Core__Option.map((ref == null) ? undefined : Caml_option.some(ref), (function (prim) {
              return prim;
            }));
      var match = props.iconBefore;
      var match$1 = props.iconAfter;
      return JsxRuntime.jsxs("button", {
                  children: [
                    loading ? JsxRuntime.jsx("span", {
                            "aria-hidden": true,
                            className: "a11y-button__spinner"
                          }) : null,
                    loading || match === undefined ? null : JsxRuntime.jsx("span", {
                            children: Caml_option.valFromOption(match),
                            "aria-hidden": true,
                            className: "a11y-button__icon-before"
                          }),
                    JsxRuntime.jsx("span", {
                          children: Core__Option.getOr(props.children, null),
                          className: "a11y-button__text"
                        }),
                    loading || match$1 === undefined ? null : JsxRuntime.jsx("span", {
                            children: Caml_option.valFromOption(match$1),
                            "aria-hidden": true,
                            className: "a11y-button__icon-after"
                          })
                  ],
                  ref: domRef,
                  "aria-disabled": busy,
                  "aria-label": props.ariaLabel,
                  "aria-busy": loading,
                  className: classes,
                  disabled: busy,
                  type: type_,
                  onClick: props.onClick
                });
    });

export {
  variantClass ,
  sizeClass ,
  make ,
}
/* make Not a pure module */
