// Generated by ReScript, PLEASE EDIT WITH CARE


var Button;

var Modal;

var version = "1.0.0";

var wcagLevel = "AA";

export {
  Button ,
  Modal ,
  version ,
  wcagLevel ,
}
/* No side effect */
