// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var DomFFI = {};

function getFocusableElements(container) {
  if (container === undefined) {
    return [];
  }
  var selector = [
      "button:not([disabled])",
      "[href]",
      "input:not([disabled])",
      "select:not([disabled])",
      "textarea:not([disabled])",
      "[tabindex]:not([tabindex=\"-1\"])"
    ].join(",");
  return Caml_option.valFromOption(container).querySelectorAll(selector);
}

function getFirstFocusable(container) {
  return getFocusableElements(container)[0];
}

function Modal(props) {
  var __className = props.className;
  var initialFocusRef = props.initialFocusRef;
  var __closeOnEscape = props.closeOnEscape;
  var __closeOnOverlayClick = props.closeOnOverlayClick;
  var __size = props.size;
  var onClose = props.onClose;
  var isOpen = props.isOpen;
  var size = __size !== undefined ? __size : "md";
  var closeOnOverlayClick = __closeOnOverlayClick !== undefined ? __closeOnOverlayClick : true;
  var closeOnEscape = __closeOnEscape !== undefined ? __closeOnEscape : true;
  var className = __className !== undefined ? __className : "";
  var titleId = React.useId();
  var contentId = React.useId();
  var overlayRef = React.useRef(null);
  var modalRef = React.useRef(null);
  var previousFocusRef = React.useRef(null);
  var match = React.useState(function () {
        return false;
      });
  var setMounted = match[1];
  React.useEffect((function () {
          setMounted(function (param) {
                return true;
              });
          return (function () {
                    setMounted(function (param) {
                          return false;
                        });
                  });
        }), []);
  React.useEffect((function () {
          if (!isOpen) {
            return ;
          }
          previousFocusRef.current = document.activeElement;
          var modalCurrent = modalRef.current;
          var initial = initialFocusRef !== undefined ? Caml_option.nullable_to_opt(initialFocusRef.current) : undefined;
          var target = initial !== undefined ? initial : getFirstFocusable((modalCurrent == null) ? undefined : Caml_option.some(modalCurrent));
          Core__Option.forEach(target, (function (prim) {
                  prim.focus();
                }));
          return (function () {
                    Core__Option.forEach(Caml_option.nullable_to_opt(previousFocusRef.current), (function (prim) {
                            prim.focus();
                          }));
                  });
        }), [
        isOpen,
        initialFocusRef
      ]);
  React.useEffect((function () {
          if (!(isOpen && closeOnEscape)) {
            return ;
          }
          var handleEscape = function (e) {
            if (e.key === "Escape") {
              return onClose();
            }

          };
          document.addEventListener("keydown", handleEscape);
          return (function () {
                    document.removeEventListener("keydown", handleEscape);
                  });
        }), [
        isOpen,
        closeOnEscape,
        onClose
      ]);
  React.useEffect((function () {
          if (!isOpen) {
            return ;
          }
          var handleTab = function (e) {
            if (e.key !== "Tab") {
              return ;
            }
            var modalCurrent = modalRef.current;
            var focusable = getFocusableElements((modalCurrent == null) ? undefined : Caml_option.some(modalCurrent));
            var len = focusable.length;
            if (len <= 0) {
              return ;
            }
            var first = focusable[0];
            var last = focusable[len - 1 | 0];
            var active = document.activeElement;
            var active$1 = (active == null) ? undefined : Caml_option.some(active);
            if (e.shiftKey) {
              if (active$1 === Caml_option.some(first)) {
                e.preventDefault();
                last.focus();
                return ;
              } else {
                return ;
              }
            } else if (active$1 === Caml_option.some(last)) {
              e.preventDefault();
              first.focus();
              return ;
            } else {
              return ;
            }
          };
          document.addEventListener("keydown", handleTab);
          return (function () {
                    document.removeEventListener("keydown", handleTab);
                  });
        }), [isOpen]);
  React.useEffect((function () {
          if (!isOpen) {
            return ;
          }
          var body = document.body;
          var originalOverflow = body.style.overflow;
          body.style.overflow = "hidden";
          return (function () {
                    body.style.overflow = originalOverflow;
                  });
        }), [isOpen]);
  var handleOverlayClick = function (e) {
    if (!closeOnOverlayClick) {
      return ;
    }
    var target = e.target;
    var o = overlayRef.current;
    if (!(o == null) && o === target) {
      return onClose();
    }

  };
  if (!isOpen || !match[0]) {
    return null;
  }
  var sizeClass = size === "lg" ? "a11y-modal--lg" : (
      size === "md" ? "a11y-modal--md" : (
          size === "sm" ? "a11y-modal--sm" : "a11y-modal--full"
        )
    );
  var modalClasses = [
        "a11y-modal",
        sizeClass,
        className
      ].filter(function (s) {
          return s !== "";
        }).join(" ");
  var modal = JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: props.title,
                              className: "a11y-modal__title",
                              id: titleId
                            }),
                        JsxRuntime.jsx("button", {
                              children: JsxRuntime.jsx("span", {
                                    children: "×",
                                    "aria-hidden": true
                                  }),
                              "aria-label": "Close dialog",
                              className: "a11y-modal__close",
                              type: "button",
                              onClick: (function (param) {
                                  onClose();
                                })
                            })
                      ],
                      className: "a11y-modal__header"
                    }),
                JsxRuntime.jsx("div", {
                      children: props.children,
                      className: "a11y-modal__content",
                      id: contentId
                    })
              ],
              ref: Caml_option.some(modalRef),
              "aria-modal": true,
              "aria-describedby": contentId,
              "aria-labelledby": titleId,
              className: modalClasses,
              role: "dialog"
            }),
        ref: Caml_option.some(overlayRef),
        className: "a11y-modal-overlay",
        role: "presentation",
        onClick: handleOverlayClick
      });
  return ReactDom.createPortal(modal, document.body);
}

var make = Modal;

export {
  DomFFI ,
  getFocusableElements ,
  getFirstFocusable ,
  make ,
}
/* react Not a pure module */
