// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Core__Int from "@rescript/core/src/Core__Int.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as Core from "@actions/core";
import * as Github from "@actions/github";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as Scanner from "@accessibility-everywhere/scanner";

var Scanner$1 = {};

var Core$1 = {};

var Github$1 = {};

function getGrade(score) {
  if (score >= 90) {
    return "A";
  } else if (score >= 80) {
    return "B";
  } else if (score >= 70) {
    return "C";
  } else if (score >= 60) {
    return "D";
  } else {
    return "F";
  }
}

function gradeEmoji(grade) {
  switch (grade) {
    case "A" :
        return "🟢";
    case "B" :
        return "🟡";
    case "C" :
        return "🟠";
    case "D" :
    case "F" :
        return "🔴";
    default:
      return "⚪";
  }
}

function impactEmoji(impact) {
  if (impact === "serious") {
    return "🟠";
  } else if (impact === "minor") {
    return "🔵";
  } else if (impact === "critical") {
    return "🔴";
  } else {
    return "🟡";
  }
}

function impactLabel(impact) {
  if (impact === "serious") {
    return "serious";
  } else if (impact === "minor") {
    return "minor";
  } else if (impact === "critical") {
    return "critical";
  } else {
    return "moderate";
  }
}

function wcagLabel(wcag) {
  if (wcag === "AA") {
    return "AA";
  } else if (wcag === "AAA") {
    return "AAA";
  } else {
    return "A";
  }
}

function parseWcagLevel(s) {
  switch (s) {
    case "A" :
        return "A";
    case "AAA" :
        return "AAA";
    default:
      return "AA";
  }
}

function generateSummary(result, url, wcagLevel) {
  var grade = getGrade(result.score);
  var g = gradeEmoji(grade);
  var parts = [
    "# Accessibility Report " + g + "\n\n",
    "**URL:** " + url + "\n",
    "**WCAG Level:** " + wcagLabel(wcagLevel) + "\n",
    "**Score:** " + result.score.toString() + "/100 (Grade " + grade + ")\n\n",
    "## Summary\n\n",
    "| Metric | Count |\n",
    "|--------|-------|\n",
    "| ✅ Passes | " + result.passes.length.toString() + " |\n",
    "| ❌ Violations | " + result.violations.length.toString() + " |\n",
    "| ⚠️ Needs Review | " + result.incomplete.length.toString() + " |\n\n"
  ];
  var head = parts.join("");
  var violations;
  if (result.violations.length > 0) {
    var shown = result.violations.slice(0, 10);
    var body = shown.map(function (v, i) {
            var e = impactEmoji(v.impact);
            return "### " + (i + 1 | 0).toString() + ". " + e + " " + v.help + "\n\n" + ("**Impact:** " + impactLabel(v.impact) + "\n\n") + ("**Description:** " + v.description + "\n\n") + ("**Instances:** " + v.nodes.length.toString() + "\n\n") + ("**Learn more:** " + v.helpUrl + "\n\n");
          }).join("");
    var more = result.violations.length > 10 ? "\n*... and " + (result.violations.length - 10 | 0).toString() + " more violations*\n\n" : "";
    violations = "## Violations\n\n" + body + more;
  } else {
    violations = "";
  }
  var footer = "\n---\n\n" + ("[View full report](https://accessibility-everywhere.org/report?url=" + encodeURIComponent(url) + ")\n");
  return head + violations + footer;
}

async function postPRComment(token, result, url, wcagLevel) {
  var octokit = Github.getOctokit(token);
  var context = Github.context;
  var pr = context.payload.pull_request;
  if (pr === undefined) {
    return ;
  }
  var summary = generateSummary(result, url, wcagLevel);
  return await octokit.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: summary
            });
}

async function run() {
  try {
    var url = Core.getInput("url", {
          required: true
        });
    var wcagLevel = parseWcagLevel(Core.getInput("wcag-level"));
    var failOnViolations = Core.getInput("fail-on-violations") === "true";
    var minScore = Core__Option.getOr(Core__Int.fromString(Core.getInput("min-score"), undefined), 0);
    var commentPR = Core.getInput("comment-pr") === "true";
    var githubToken = Core.getInput("github-token");
    Core.info("Scanning " + url + " for WCAG " + wcagLabel(wcagLevel) + " compliance...");
    var scanner = Scanner.createScanner();
    var result = await scanner.scan({
          url: url,
          wcagLevel: wcagLevel,
          screenshot: false
        });
    Core.setOutput("score", result.score);
    Core.setOutput("violations", result.violations.length);
    Core.setOutput("passes", result.passes.length);
    Core.setOutput("report-url", "https://accessibility-everywhere.org/report?url=" + encodeURIComponent(url));
    var summary = generateSummary(result, url, wcagLevel);
    await Core.summary.addRaw(summary).write();
    if (commentPR && githubToken !== "" && Github.context.payload.pull_request !== undefined) {
      await postPRComment(githubToken, result, url, wcagLevel);
    }
    var bar = "============================================================";
    Core.info("\n" + bar);
    Core.info("Accessibility Score: " + result.score.toString() + "/100");
    Core.info("Violations: " + result.violations.length.toString());
    Core.info("Passes: " + result.passes.length.toString());
    Core.info("Incomplete: " + result.incomplete.length.toString());
    Core.info(bar + "\n");
    if (result.violations.length > 0) {
      Core.warning("Found " + result.violations.length.toString() + " accessibility violations:");
      result.violations.forEach(function (v, i) {
            Core.warning((i + 1 | 0).toString() + ". [" + impactLabel(v.impact).toUpperCase() + "] " + v.description);
            Core.warning("   Help: " + v.helpUrl);
            Core.warning("   Instances: " + v.nodes.length.toString());
          });
    }
    if (failOnViolations && result.violations.length > 0) {
      Core.setFailed("Found " + result.violations.length.toString() + " accessibility violations");
    }
    if (minScore > 0 && result.score < minScore) {
      Core.setFailed("Accessibility score " + result.score.toString() + " is below minimum required score " + minScore.toString());
    }
    if (result.violations.length === 0 && result.score >= minScore) {
      Core.info("✓ Accessibility check passed!");
      return ;
    } else {
      return ;
    }
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      Core.setFailed("Action failed: " + Core__Option.getOr(err._1.message, "unknown error"));
      return ;
    }
    throw err;
  }
}

run();

export {
  Scanner$1 as Scanner,
  Core$1 as Core,
  Github$1 as Github,
  getGrade ,
  gradeEmoji ,
  impactEmoji ,
  impactLabel ,
  wcagLabel ,
  parseWcagLevel ,
  generateSummary ,
  postPRComment ,
  run ,
}
/*  Not a pure module */
