// Generated by ReScript, PLEASE EDIT WITH CARE

import Ora from "ora";
import * as Path from "path";
import Chalk from "chalk";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as FsExtra from "fs-extra";
import * as Core__Int from "@rescript/core/src/Core__Int.mjs";
import * as Commander from "commander";
import CliTable3 from "cli-table3";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as Scanner from "@accessibility-everywhere/scanner";

var Scanner$1 = {};

var Commander$1 = {};

var Chalk$1 = {};

var Ora$1 = {};

var Table = {};

var Fs = {};

var Path$1 = {};

var Process = {};

var chalk = Chalk;

function getGrade(score) {
  if (score >= 90) {
    return "A";
  } else if (score >= 80) {
    return "B";
  } else if (score >= 70) {
    return "C";
  } else if (score >= 60) {
    return "D";
  } else {
    return "F";
  }
}

var bar = "=".repeat(70);

function parseWcagLevel(s) {
  switch (s) {
    case "A" :
        return "A";
    case "AAA" :
        return "AAA";
    default:
      return "AA";
  }
}

function wcagLabel(w) {
  if (w === "AA") {
    return "AA";
  } else if (w === "AAA") {
    return "AAA";
  } else {
    return "A";
  }
}

function impactColored(impact) {
  var label = impact === "serious" ? "serious" : (
      impact === "minor" ? "minor" : (
          impact === "critical" ? "critical" : "moderate"
        )
    );
  if (impact === "serious") {
    return chalk.red(label);
  } else if (impact === "minor") {
    return chalk.blue(label);
  } else if (impact === "critical") {
    return chalk.bold.red(label);
  } else {
    return chalk.yellow(label);
  }
}

function scoreColored(score) {
  if (score >= 90) {
    return chalk.bold.green(score.toString());
  } else if (score >= 70) {
    return chalk.bold.yellow(score.toString());
  } else {
    return chalk.bold.red(score.toString());
  }
}

function generateMarkdown(result, url) {
  var header = "# Accessibility Report\n\n**URL:** " + url + "\n**Score:** " + result.score.toString() + "/100\n\n## Violations\n\n";
  var body = result.violations.map(function (v, i) {
          return "### " + (i + 1 | 0).toString() + ". " + v.help + "\n\n" + ("- **Impact:** " + v.impact + "\n") + ("- **Instances:** " + v.nodes.length.toString() + "\n") + ("- **Help:** " + v.helpUrl + "\n\n");
        }).join("");
  return header + body;
}

async function scanAction(url, options) {
  var spinner = Ora("Scanning for accessibility issues...").start();
  try {
    var scanner = Scanner.createScanner();
    var result = await scanner.scan({
          url: url,
          wcagLevel: parseWcagLevel(options.level),
          screenshot: options.screenshot
        });
    spinner.succeed("Scan complete!");
    console.log("\n" + bar);
    console.log(chalk.bold.blue("Accessibility Report"));
    console.log(bar);
    console.log("URL: " + url);
    console.log("WCAG Level: " + options.level);
    console.log("Score: " + scoreColored(result.score) + "/100 (Grade " + getGrade(result.score) + ")");
    console.log(bar + "\n");
    var summaryTable = new CliTable3({
          head: [
            "Metric",
            "Count"
          ],
          colWidths: [
            30,
            10
          ]
        });
    summaryTable.push([
          "✅ Passes",
          result.passes.length.toString()
        ]);
    summaryTable.push([
          "❌ Violations",
          result.violations.length.toString()
        ]);
    summaryTable.push([
          "⚠️  Needs Review",
          result.incomplete.length.toString()
        ]);
    console.log(summaryTable.toString() + "\n");
    if (result.violations.length > 0) {
      console.log(chalk.bold.red("Found " + result.violations.length.toString() + " violations:\n"));
      var format = options.format;
      if (format === "table") {
        var violationsTable = new CliTable3({
              head: [
                "Impact",
                "Description",
                "Instances",
                "WCAG"
              ],
              colWidths: [
                12,
                50,
                10,
                15
              ]
            });
        result.violations.forEach(function (v) {
              violationsTable.push([
                    impactColored(v.impact),
                    v.description,
                    v.nodes.length.toString(),
                    v.tags.join(", ")
                  ]);
            });
        console.log(violationsTable.toString());
      } else if (format === "markdown") {
        console.log(generateMarkdown(result, url));
      } else {
        console.log(JSON.stringify(result, null, 2));
      }
    } else {
      console.log(chalk.bold.green("🎉 No violations found! Great job!"));
    }
    var out = options.output;
    if (out !== undefined) {
      await FsExtra.writeJson(out, result, {
            spaces: 2
          });
      console.log(chalk.gray("\n✓ Results saved to " + out));
    }
    return process.exit(result.violations.length > 0 ? 1 : 0);
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      spinner.fail("Scan failed");
      console.error(chalk.red(Core__Option.getOr(err._1.message, "unknown error")));
      return process.exit(1);
    }
    throw err;
  }
}

async function ciAction(url, options) {
  var spinner = Ora("Running CI scan...").start();
  try {
    var scanner = Scanner.createScanner();
    var result = await scanner.scan({
          url: url,
          wcagLevel: parseWcagLevel(options.level)
        });
    spinner.succeed("CI scan complete");
    var minScore = Core__Option.getOr(Core__Int.fromString(options.minScore, undefined), 70);
    var failOnViolations = Core__Option.getOr(options.failOnViolations, false);
    console.log("Score: " + result.score.toString() + "/100");
    console.log("Violations: " + result.violations.length.toString());
    if (failOnViolations && result.violations.length > 0) {
      console.error(chalk.red("✗ Failed: Found " + result.violations.length.toString() + " violations"));
      process.exit(1);
    }
    if (result.score < minScore) {
      console.error(chalk.red("✗ Failed: Score " + result.score.toString() + " below minimum " + minScore.toString()));
      process.exit(1);
    }
    console.log(chalk.green("✓ Passed all checks"));
    return process.exit(0);
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      spinner.fail("CI scan failed");
      console.error(chalk.red(Core__Option.getOr(err._1.message, "unknown error")));
      return process.exit(1);
    }
    throw err;
  }
}

async function batchAction(file, options) {
  try {
    var raw = await FsExtra.readFile(file, "utf-8");
    var urls = raw.split("\n").map(function (prim) {
            return prim.trim();
          }).filter(function (s) {
          if (s !== "") {
            return !s.startsWith("#");
          } else {
            return false;
          }
        });
    console.log(chalk.blue("Scanning " + urls.length.toString() + " URLs..."));
    var outDir = Core__Option.getOr(options.output, "./scan-results");
    await FsExtra.ensureDir(outDir);
    var scanner = Scanner.createScanner();
    var completed = 0;
    var failed = 0;
    var total = urls.length;
    for(var i = 0; i < total; ++i){
      var url = urls[i];
      var spinner = Ora("[" + (i + 1 | 0).toString() + "/" + total.toString() + "] " + url).start();
      try {
        var result = await scanner.scan({
              url: url,
              wcagLevel: parseWcagLevel(options.level)
            });
        var safeName = url.replace(/[^a-z0-9]/gi, "_") + ".json";
        var filepath = Path.join(outDir, safeName);
        await FsExtra.writeJson(filepath, result, {
              spaces: 2
            });
        spinner.succeed(url + " - Score: " + result.score.toString());
        completed = completed + 1 | 0;
      }
      catch (raw_err){
        var err = Caml_js_exceptions.internalToOCamlException(raw_err);
        if (err.RE_EXN_ID === Js_exn.$$Error) {
          spinner.fail(url + " - " + Core__Option.getOr(err._1.message, "unknown error"));
          failed = failed + 1 | 0;
        } else {
          throw err;
        }
      }
    }
    console.log(chalk.green("\n✓ Completed: " + completed.toString()));
    if (failed > 0) {
      console.log(chalk.red("✗ Failed: " + failed.toString()));
      return ;
    } else {
      return ;
    }
  }
  catch (raw_err$1){
    var err$1 = Caml_js_exceptions.internalToOCamlException(raw_err$1);
    if (err$1.RE_EXN_ID === Js_exn.$$Error) {
      console.error(chalk.red(Core__Option.getOr(err$1._1.message, "unknown error")));
      return process.exit(1);
    }
    throw err$1;
  }
}

var program = new Commander.Command().name("accessibility-scan").description("Command-line tool for accessibility scanning").version("1.0.0");

program.command("scan").description("Scan a URL for accessibility issues").argument("<url>", "URL to scan").option("-l, --level <level>", "WCAG level (A, AA, AAA)", "AA").option("-o, --output <file>", "Output file for results (JSON)").option("-f, --format <format>", "Output format (json, table, markdown)", "table").option("--screenshot", "Take screenshot").action(scanAction);

program.command("ci").description("Run accessibility scan for CI/CD").argument("<url>", "URL to scan").option("-l, --level <level>", "WCAG level (A, AA, AAA)", "AA").option("--min-score <score>", "Minimum required score", "70").option("--fail-on-violations", "Fail if any violations found").action(ciAction);

program.command("batch").description("Scan multiple URLs from a file").argument("<file>", "File containing URLs (one per line)").option("-l, --level <level>", "WCAG level (A, AA, AAA)", "AA").option("-o, --output <dir>", "Output directory for results", "./scan-results").action(batchAction);

program.parse();

export {
  Scanner$1 as Scanner,
  Commander$1 as Commander,
  Chalk$1 as Chalk,
  Ora$1 as Ora,
  Table ,
  Fs ,
  Path$1 as Path,
  Process ,
  chalk ,
  getGrade ,
  bar ,
  parseWcagLevel ,
  wcagLabel ,
  impactColored ,
  scoreColored ,
  generateMarkdown ,
  scanAction ,
  ciAction ,
  batchAction ,
  program ,
}
/* chalk Not a pure module */
