// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Arangojs from "arangojs";

var Arango = {};

function make(config) {
  var db = new Arangojs.Database({
        url: config.url,
        databaseName: config.database,
        auth: {
          username: config.username,
          password: config.password
        }
      });
  return {
          db: db,
          sites: undefined,
          scans: undefined,
          violations: undefined,
          wcagCriteria: undefined,
          organizations: undefined,
          siteScans: undefined,
          scanViolations: undefined,
          violationCriteria: undefined,
          orgSites: undefined
        };
}

function getWCAGCriteriaData() {
  return [
          {
            _key: "1_1_1",
            criterion: "1.1.1",
            level: "A",
            principle: "perceivable",
            guideline: "1.1",
            title: "Non-text Content",
            description: "All non-text content has a text alternative",
            successCriteria: "Provide text alternatives for any non-text content",
            techniques: [
              "H37",
              "H36",
              "G94",
              "G95"
            ],
            failures: [
              "F3",
              "F13",
              "F20",
              "F30",
              "F38",
              "F39",
              "F65",
              "F67",
              "F71",
              "F72"
            ]
          },
          {
            _key: "1_3_1",
            criterion: "1.3.1",
            level: "A",
            principle: "perceivable",
            guideline: "1.3",
            title: "Info and Relationships",
            description: "Information, structure, and relationships can be programmatically determined",
            successCriteria: "Information, structure, and relationships conveyed through presentation can be programmatically determined",
            techniques: [
              "H42",
              "H43",
              "H44",
              "H48",
              "H51",
              "H63",
              "H71",
              "H73",
              "H85"
            ],
            failures: [
              "F2",
              "F33",
              "F34",
              "F42",
              "F43",
              "F46",
              "F48",
              "F68",
              "F87",
              "F90",
              "F91",
              "F92"
            ]
          },
          {
            _key: "1_4_3",
            criterion: "1.4.3",
            level: "AA",
            principle: "perceivable",
            guideline: "1.4",
            title: "Contrast (Minimum)",
            description: "Text has a contrast ratio of at least 4.5:1",
            successCriteria: "The visual presentation of text and images of text has a contrast ratio of at least 4.5:1",
            techniques: [
              "G17",
              "G18",
              "G145",
              "G148",
              "G174"
            ],
            failures: [
              "F24",
              "F83"
            ]
          },
          {
            _key: "2_1_1",
            criterion: "2.1.1",
            level: "A",
            principle: "operable",
            guideline: "2.1",
            title: "Keyboard",
            description: "All functionality is available from a keyboard",
            successCriteria: "All functionality of the content is operable through a keyboard interface",
            techniques: [
              "G202",
              "H91"
            ],
            failures: [
              "F54",
              "F55",
              "F42"
            ]
          },
          {
            _key: "2_4_1",
            criterion: "2.4.1",
            level: "A",
            principle: "operable",
            guideline: "2.4",
            title: "Bypass Blocks",
            description: "A mechanism is available to bypass blocks of content",
            successCriteria: "A mechanism is available to bypass blocks of content that are repeated on multiple Web pages",
            techniques: [
              "G1",
              "G123",
              "G124",
              "H69",
              "H70"
            ],
            failures: ["F"]
          },
          {
            _key: "2_4_2",
            criterion: "2.4.2",
            level: "A",
            principle: "operable",
            guideline: "2.4",
            title: "Page Titled",
            description: "Web pages have titles that describe topic or purpose",
            successCriteria: "Web pages have titles that describe topic or purpose",
            techniques: [
              "G88",
              "H25"
            ],
            failures: ["F25"]
          },
          {
            _key: "3_1_1",
            criterion: "3.1.1",
            level: "A",
            principle: "understandable",
            guideline: "3.1",
            title: "Language of Page",
            description: "The default human language can be programmatically determined",
            successCriteria: "The default human language of each Web page can be programmatically determined",
            techniques: ["H57"],
            failures: []
          },
          {
            _key: "3_2_3",
            criterion: "3.2.3",
            level: "AA",
            principle: "understandable",
            guideline: "3.2",
            title: "Consistent Navigation",
            description: "Navigation mechanisms are consistent",
            successCriteria: "Navigational mechanisms that are repeated on multiple Web pages occur in the same relative order",
            techniques: ["G61"],
            failures: ["F66"]
          },
          {
            _key: "4_1_1",
            criterion: "4.1.1",
            level: "A",
            principle: "robust",
            guideline: "4.1",
            title: "Parsing",
            description: "Content can be parsed by user agents",
            successCriteria: "Elements have complete start and end tags, are nested according to specifications",
            techniques: [
              "G134",
              "G192",
              "H88",
              "H74",
              "H93",
              "H94"
            ],
            failures: [
              "F70",
              "F77"
            ]
          },
          {
            _key: "4_1_2",
            criterion: "4.1.2",
            level: "A",
            principle: "robust",
            guideline: "4.1",
            title: "Name, Role, Value",
            description: "User interface components have programmatically determined name, role, and value",
            successCriteria: "For all user interface components, the name and role can be programmatically determined",
            techniques: [
              "G108",
              "H91",
              "H44",
              "H64",
              "H65",
              "H88"
            ],
            failures: [
              "F15",
              "F20",
              "F59",
              "F68",
              "F79",
              "F86",
              "F89"
            ]
          }
        ];
}

async function createCollectionIfNotExists(db, name) {
  var collections = await db.listCollections();
  if (!collections.some(function (c) {
          return c.name === name;
        })) {
    await db.createCollection(name);
    return ;
  }

}

async function createEdgeCollectionIfNotExists(db, name) {
  var collections = await db.listCollections();
  if (!collections.some(function (c) {
          return c.name === name;
        })) {
    await db.createEdgeCollection(name);
    return ;
  }

}

async function createIndexes(svc) {
  await svc.sites.ensureIndex({
        type: "persistent",
        fields: ["url"],
        unique: true
      });
  await svc.sites.ensureIndex({
        type: "persistent",
        fields: ["domain"]
      });
  await svc.sites.ensureIndex({
        type: "persistent",
        fields: ["currentScore"]
      });
  await svc.scans.ensureIndex({
        type: "persistent",
        fields: ["siteKey"]
      });
  await svc.scans.ensureIndex({
        type: "persistent",
        fields: ["timestamp"]
      });
  await svc.scans.ensureIndex({
        type: "persistent",
        fields: ["score"]
      });
  await svc.violations.ensureIndex({
        type: "persistent",
        fields: ["scanKey"]
      });
  await svc.violations.ensureIndex({
        type: "persistent",
        fields: ["siteKey"]
      });
  await svc.violations.ensureIndex({
        type: "persistent",
        fields: ["wcagCriterion"]
      });
  await svc.violations.ensureIndex({
        type: "persistent",
        fields: ["impact"]
      });
  await svc.violations.ensureIndex({
        type: "persistent",
        fields: ["fixed"]
      });
  await svc.wcagCriteria.ensureIndex({
        type: "persistent",
        fields: ["criterion"],
        unique: true
      });
  await svc.wcagCriteria.ensureIndex({
        type: "persistent",
        fields: ["level"]
      });
  await svc.organizations.ensureIndex({
        type: "persistent",
        fields: ["domain"]
      });
  return await svc.organizations.ensureIndex({
              type: "persistent",
              fields: ["apiKey"],
              unique: true,
              sparse: true
            });
}

async function initializeWCAGCriteria(svc) {
  var countResult = await svc.wcagCriteria.count();
  if (countResult.count !== 0) {
    return ;
  }
  var criteria = getWCAGCriteriaData();
  for(var i = 0 ,i_finish = criteria.length; i < i_finish; ++i){
    var c = criteria[i];
    await svc.wcagCriteria.save(c);
  }
}

async function initialize(svc) {
  var databases = await svc.db.listDatabases();
  var dbName = svc.db.name;
  if (!databases.includes(dbName)) {
    await svc.db.createDatabase(dbName);
  }
  await createCollectionIfNotExists(svc.db, "sites");
  await createCollectionIfNotExists(svc.db, "scans");
  await createCollectionIfNotExists(svc.db, "violations");
  await createCollectionIfNotExists(svc.db, "wcag_criteria");
  await createCollectionIfNotExists(svc.db, "organizations");
  await createEdgeCollectionIfNotExists(svc.db, "site_scans");
  await createEdgeCollectionIfNotExists(svc.db, "scan_violations");
  await createEdgeCollectionIfNotExists(svc.db, "violation_criteria");
  await createEdgeCollectionIfNotExists(svc.db, "org_sites");
  svc.sites = svc.db.collection("sites");
  svc.scans = svc.db.collection("scans");
  svc.violations = svc.db.collection("violations");
  svc.wcagCriteria = svc.db.collection("wcag_criteria");
  svc.organizations = svc.db.collection("organizations");
  svc.siteScans = svc.db.collection("site_scans");
  svc.scanViolations = svc.db.collection("scan_violations");
  svc.violationCriteria = svc.db.collection("violation_criteria");
  svc.orgSites = svc.db.collection("org_sites");
  await createIndexes(svc);
  return await initializeWCAGCriteria(svc);
}

async function getSiteByUrl(svc, url) {
  var cursor = await svc.db.query("FOR site IN sites FILTER site.url == @url LIMIT 1 RETURN site", {
        url: url
      });
  var results = await cursor.all();
  if (results.length > 0) {
    return results[0];
  }

}

async function getRecentScansForSite(svc, siteKey, limitOpt) {
  var limit = limitOpt !== undefined ? limitOpt : 10;
  var cursor = await svc.db.query("FOR scan IN scans FILTER scan.siteKey == @siteKey SORT scan.timestamp DESC LIMIT @limit RETURN scan", {
        siteKey: siteKey,
        limit: limit
      });
  return await cursor.all();
}

async function getViolationsForScan(svc, scanKey) {
  var cursor = await svc.db.query("FOR violation IN violations FILTER violation.scanKey == @scanKey SORT violation.impact DESC RETURN violation", {
        scanKey: scanKey
      });
  return await cursor.all();
}

async function getTopSites(svc, limitOpt) {
  var limit = limitOpt !== undefined ? limitOpt : 100;
  var cursor = await svc.db.query("FOR site IN sites FILTER site.currentScore > 0 SORT site.currentScore DESC LIMIT @limit RETURN site", {
        limit: limit
      });
  return await cursor.all();
}

async function getCommonViolations(svc, limitOpt) {
  var limit = limitOpt !== undefined ? limitOpt : 10;
  var cursor = await svc.db.query("FOR violation IN violations COLLECT wcagCriterion = violation.wcagCriterion WITH COUNT INTO count SORT count DESC LIMIT @limit RETURN {criterion: wcagCriterion, count: count}", {
        limit: limit
      });
  return await cursor.all();
}

async function getSiteViolationTrend(svc, siteKey, daysOpt) {
  var days = daysOpt !== undefined ? daysOpt : 30;
  var startDate = new Date();
  startDate.setDate(startDate.getDate() - days | 0);
  var cursor = await svc.db.query("FOR scan IN scans FILTER scan.siteKey == @siteKey AND scan.timestamp >= @startDate SORT scan.timestamp ASC RETURN {timestamp: scan.timestamp, violations: scan.violations, score: scan.score}", {
        siteKey: siteKey,
        startDate: startDate
      });
  return await cursor.all();
}

async function getOrganizationSites(svc, orgKey) {
  var cursor = await svc.db.query("FOR org IN organizations FILTER org._key == @orgKey FOR v, e IN 1..1 OUTBOUND org org_sites RETURN v", {
        orgKey: orgKey
      });
  return await cursor.all();
}

function createArangoDBService(config) {
  var defaults_url = (process.env.ARANGO_URL || "http://localhost:8529");
  var defaults_database = (process.env.ARANGO_DATABASE || "accessibility");
  var defaults_username = (process.env.ARANGO_USERNAME || "root");
  var defaults_password = (process.env.ARANGO_PASSWORD || "development");
  var defaults = {
    url: defaults_url,
    database: defaults_database,
    username: defaults_username,
    password: defaults_password
  };
  var merged = config !== undefined ? config : defaults;
  return make(merged);
}

export {
  Arango ,
  make ,
  getWCAGCriteriaData ,
  createCollectionIfNotExists ,
  createEdgeCollectionIfNotExists ,
  createIndexes ,
  initializeWCAGCriteria ,
  initialize ,
  getSiteByUrl ,
  getRecentScansForSite ,
  getViolationsForScan ,
  getTopSites ,
  getCommonViolations ,
  getSiteViolationTrend ,
  getOrganizationSites ,
  createArangoDBService ,
}
/* arangojs Not a pure module */
