// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Result from "@rescript/core/src/Core__Result.mjs";

function validate(s) {
  var trimmed = s.trim();
  if (trimmed === "") {
    return {
            TAG: "Error",
            _0: "selector is empty"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              TAG: "Selector",
              _0: trimmed
            }
          };
  }
}

function value(s) {
  return s._0;
}

var ProvenSelector = {
  validate: validate,
  value: value
};

function validate$1(s) {
  if (s.toLowerCase().includes("<script")) {
    return {
            TAG: "Error",
            _0: "script tags are not allowed"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              TAG: "Html",
              _0: s
            }
          };
  }
}

function value$1(h) {
  return h._0;
}

var ProvenHTML = {
  validate: validate$1,
  value: value$1
};

function mount(sel, html) {
  var selStr = sel._0;
  var htmlStr = html._0;
  var node = document.querySelector(selStr);
  if (node == null) {
    return {
            TAG: "MountPointNotFound",
            _0: selStr
          };
  } else {
    node.innerHTML = htmlStr;
    return {
            TAG: "Mounted",
            _0: node
          };
  }
}

function mountSafe(selector, html, onSuccess, onError) {
  var e = validate(selector);
  if (e.TAG !== "Ok") {
    return onError("Invalid selector: " + e._0);
  }
  var e$1 = validate$1(html);
  if (e$1.TAG !== "Ok") {
    return onError("Invalid HTML: " + e$1._0);
  }
  var el = mount(e._0, e$1._0);
  switch (el.TAG) {
    case "Mounted" :
        return onSuccess(el._0);
    case "MountPointNotFound" :
        return onError("Mount point not found: " + el._0);
    case "InvalidSelector" :
        return onError("Invalid selector: " + el._0);
    case "InvalidHTML" :
        return onError("Invalid HTML: " + el._0);
    
  }
}

function mountWhenReady(selector, html, onSuccess, onError) {
  var run = function () {
    mountSafe(selector, html, onSuccess, onError);
  };
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", run);
    return ;
  } else {
    return run();
  }
}

function mountBatch(specs) {
  var validated = Core__Array.reduce(specs, {
        TAG: "Ok",
        _0: []
      }, (function (acc, spec) {
          return Core__Result.flatMap(acc, (function (arr) {
                        var match = validate(spec.selector);
                        var match$1 = validate$1(spec.html);
                        if (match.TAG !== "Ok") {
                          return {
                                  TAG: "Error",
                                  _0: "Invalid selector " + spec.selector + ": " + match._0
                                };
                        }
                        if (match$1.TAG !== "Ok") {
                          return {
                                  TAG: "Error",
                                  _0: "Invalid HTML for " + spec.selector + ": " + match$1._0
                                };
                        }
                        arr.push([
                              match._0,
                              match$1._0
                            ]);
                        return {
                                TAG: "Ok",
                                _0: arr
                              };
                      }));
        }));
  return Core__Result.flatMap(validated, (function (pairs) {
                var missing = Core__Array.reduce(pairs, [], (function (acc, param) {
                        var s = param[0]._0;
                        var match = document.querySelector(s);
                        if (match == null) {
                          acc.push(s);
                          return acc;
                        } else {
                          return acc;
                        }
                      }));
                if (missing.length > 0) {
                  return {
                          TAG: "Error",
                          _0: "Mount points not found: " + missing.join(", ")
                        };
                } else {
                  return Core__Array.reduce(pairs, {
                              TAG: "Ok",
                              _0: []
                            }, (function (acc, param) {
                                var h = param[1];
                                var sel = param[0];
                                return Core__Result.flatMap(acc, (function (arr) {
                                              var el = mount(sel, h);
                                              switch (el.TAG) {
                                                case "Mounted" :
                                                    arr.push(el._0);
                                                    return {
                                                            TAG: "Ok",
                                                            _0: arr
                                                          };
                                                case "MountPointNotFound" :
                                                    return {
                                                            TAG: "Error",
                                                            _0: "Mount point disappeared: " + el._0
                                                          };
                                                case "InvalidSelector" :
                                                    return {
                                                            TAG: "Error",
                                                            _0: "Validation inconsistency (selector): " + el._0
                                                          };
                                                case "InvalidHTML" :
                                                    return {
                                                            TAG: "Error",
                                                            _0: "Validation inconsistency (html): " + el._0
                                                          };
                                                
                                              }
                                            }));
                              }));
                }
              }));
}

export {
  ProvenSelector ,
  ProvenHTML ,
  mount ,
  mountSafe ,
  mountWhenReady ,
  mountBatch ,
}
/* No side effect */
