// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SafeDOM from "./SafeDOM.mjs";

function mountApp() {
  SafeDOM.mountSafe("#app", "<div><h1>Hello, World!</h1><p>Mounted safely with proofs.</p></div>", (function (el) {
          console.log("✓ App mounted successfully!");
          console.log("Element:", el);
        }), (function (err) {
          console.error("✗ Mount failed:", err);
        }));
}

function mountWhenDOMReady() {
  SafeDOM.mountWhenReady("#app", "<div class='container'><h1>App Title</h1></div>", (function (param) {
          console.log("✓ Mounted after DOM ready");
        }), (function (err) {
          console.error("✗ Failed:", err);
        }));
}

function mountMultiple() {
  var specs = [
    {
      selector: "#header",
      html: "<header><h1>Site Title</h1></header>"
    },
    {
      selector: "#nav",
      html: "<nav><a href='/'>Home</a></nav>"
    },
    {
      selector: "#main",
      html: "<main><p>Content here</p></main>"
    },
    {
      selector: "#footer",
      html: "<footer>© 2026</footer>"
    }
  ];
  var elements = SafeDOM.mountBatch(specs);
  if (elements.TAG === "Ok") {
    var elements$1 = elements._0;
    console.log("✓ Successfully mounted " + elements$1.length.toString() + " elements");
    elements$1.forEach(function (el) {
          console.log("  -", el);
        });
    return ;
  }
  console.error("✗ Batch mount failed:", elements._0);
  console.error("  (None were mounted - atomic operation)");
}

function mountWithValidation() {
  var e = SafeDOM.ProvenSelector.validate("#my-app");
  if (e.TAG === "Ok") {
    var e$1 = SafeDOM.ProvenHTML.validate("<div>Content</div>");
    if (e$1.TAG === "Ok") {
      var el = SafeDOM.mount(e._0, e$1._0);
      switch (el.TAG) {
        case "Mounted" :
            console.log("✓ Mounted with validated inputs:", el._0);
            return ;
        case "MountPointNotFound" :
            console.error("✗ Element not found: " + el._0);
            return ;
        case "InvalidSelector" :
        case "InvalidHTML" :
            console.error("Impossible - already validated");
            return ;
        
      }
    } else {
      console.error("Invalid HTML: " + e$1._0);
      return ;
    }
  } else {
    console.error("Invalid selector: " + e._0);
    return ;
  }
}

function init() {
  return {
          message: "Hello from TEA"
        };
}

function update(model, _msg) {
  return model;
}

function view(model) {
  return "<div><h1>" + model.message + "</h1></div>";
}

var MyApp = {
  init: init,
  update: update,
  view: view
};

function mountTEAApp() {
  var model = {
    message: "Hello from TEA"
  };
  var html = view(model);
  SafeDOM.mountWhenReady("#tea-app", html, (function (_el) {
          console.log("✓ TEA app mounted");
        }), (function (err) {
          console.error("✗ TEA mount failed: " + err);
        }));
}

function main() {
  console.log("SafeDOM Examples");
  console.log("================\n");
  mountWhenDOMReady();
}

main();

export {
  mountApp ,
  mountWhenDOMReady ,
  mountMultiple ,
  mountWithValidation ,
  MyApp ,
  mountTEAApp ,
  main ,
}
/*  Not a pure module */
