// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Joi from "joi";
import Cors from "cors";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Dotenv from "dotenv";
import Helmet from "helmet";
import * as Express from "express";
import Express$1 from "express";
import * as Core__Int from "@rescript/core/src/Core__Int.mjs";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Core__JSON from "@rescript/core/src/Core__JSON.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import Compression from "compression";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as Core__Promise from "@rescript/core/src/Core__Promise.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import ExpressRateLimit from "express-rate-limit";
import * as Core from "@accessibility-everywhere/core";
import * as Scanner from "@accessibility-everywhere/scanner";

Dotenv.config();

var db = Core.createArangoDBService();

var scanner = Scanner.createScanner();

var app = Express$1();

var s = process.env.PORT;

var port;

switch (s) {
  case "" :
  case "undefined" :
      port = 3000;
      break;
  default:
    port = Core__Option.getOr(Core__Int.fromString(s, undefined), 3000);
}

function nowIso() {
  return (new Date().toISOString());
}

function nowDate() {
  return new Date();
}

app.use(Helmet());

app.use(Cors());

app.use(Compression());

app.use(Express.default.json({
          limit: "10mb"
        }));

var limiter = ExpressRateLimit({
      windowMs: 900000,
      max: 100,
      message: "Too many requests from this IP, please try again later."
    });

app.use("/v1/", limiter);

async function initializeDatabase() {
  try {
    await Core.initialize(db);
    console.log("✓ Database initialized successfully");
    return ;
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      console.error("✗ Database initialization failed:", err._1);
      return (process.exit(1));
    }
    throw err;
  }
}

function respondError(res, status, message) {
  res.status(status);
  res.json({
        error: {
          message: message,
          status: status
        }
      });
}

app.get("/health", (async function (_req, res, _next) {
        res.json({
              status: "healthy",
              timestamp: nowIso(),
              version: "1.0.0"
            });
      }));

app.get("/v1", (async function (_req, res, _next) {
        res.json({
              name: "Accessibility Everywhere Monitoring API",
              version: "1.0.0",
              description: "Accessibility violation reporting and analytics API",
              endpoints: {
                scan: "/v1/scan",
                violations: "/v1/violations",
                leaderboard: "/v1/leaderboard",
                badge: "/v1/badge/:domain",
                stats: "/v1/stats",
                dashboard: "/v1/dashboard/:orgId"
              },
              documentation: "https://docs.accessibility-everywhere.org/api"
            });
      }));

var scanRouter = Express.default.Router();

var scanSchema = Joi.object(Object.fromEntries([
          [
            "url",
            Joi.string().uri().required()
          ],
          [
            "wcagLevel",
            Joi.string().valid([
                    "A",
                    "AA",
                    "AAA"
                  ]).default("AA")
          ],
          [
            "screenshot",
            Joi.boolean().default(false)
          ]
        ]));

function parseWcagLevel(s) {
  switch (s) {
    case "A" :
        return "A";
    case "AAA" :
        return "AAA";
    default:
      return "AA";
  }
}

scanRouter.post("/", (async function (req, res, next) {
        try {
          var result = scanSchema.validate(req.body);
          var err = result.error;
          if (err !== undefined) {
            var msg = err.details[0];
            return respondError(res, 400, msg.message);
          }
          var value = result.value;
          var url = Core__Option.getOr(Core__JSON.Decode.string(value["url"]), "");
          var wcagLevelStr = Core__Option.getOr(Core__JSON.Decode.string(value["wcagLevel"]), "AA");
          var wcagLevel = parseWcagLevel(wcagLevelStr);
          var screenshot = Core__Option.getOr(Core__JSON.Decode.bool(value["screenshot"]), false);
          var scanResult = await scanner.scan({
                url: url,
                wcagLevel: wcagLevel,
                screenshot: screenshot
              });
          var urlObj = new URL(url);
          var domain = urlObj.hostname;
          var existingSite = await Core.getSiteByUrl(db, url);
          var siteKey = existingSite !== undefined ? (await db.sites.update(existingSite._key, {
                    lastScanned: new Date(),
                    scanCount: existingSite.scanCount + 1 | 0,
                    previousScore: existingSite.currentScore,
                    currentScore: scanResult.score
                  }), existingSite._key) : (await db.sites.save({
                    url: url,
                    domain: domain,
                    firstScanned: new Date(),
                    lastScanned: new Date(),
                    scanCount: 1,
                    currentScore: scanResult.score,
                    status: "active"
                  }))._key;
          var scanDoc = await db.scans.save({
                siteKey: siteKey,
                timestamp: scanResult.timestamp,
                score: scanResult.score,
                violations: scanResult.violations.length,
                passes: scanResult.passes.length,
                incomplete: scanResult.incomplete.length,
                url: url,
                wcagLevel: wcagLevelStr,
                duration: scanResult.duration,
                userAgent: scanResult.metadata.userAgent
              });
          for(var vi = 0 ,vi_finish = scanResult.violations.length; vi < vi_finish; ++vi){
            var v = scanResult.violations[vi];
            for(var ni = 0 ,ni_finish = v.nodes.length; ni < ni_finish; ++ni){
              var node = v.nodes[ni];
              await db.violations.save({
                    scanKey: scanDoc._key,
                    siteKey: siteKey,
                    wcagCriterion: Core__Option.getOr(v.wcag[0], "unknown"),
                    wcagLevel: wcagLevelStr,
                    impact: v.impact,
                    description: v.description,
                    helpUrl: v.helpUrl,
                    selector: node.target.join(" > "),
                    html: node.html,
                    timestamp: new Date(),
                    fixed: false
                  });
            }
          }
          res.json({
                success: true,
                data: {
                  url: url,
                  scanId: scanDoc._key,
                  score: scanResult.score,
                  violations: scanResult.violations.length,
                  passes: scanResult.passes.length,
                  incomplete: scanResult.incomplete.length,
                  wcagLevel: wcagLevelStr,
                  timestamp: scanResult.timestamp,
                  details: {
                    violations: scanResult.violations,
                    passes: scanResult.passes,
                    incomplete: scanResult.incomplete
                  }
                }
              });
          return ;
        }
        catch (raw_err){
          var err$1 = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err$1.RE_EXN_ID === Js_exn.$$Error) {
            next(err$1._1);
            return ;
          }
          throw err$1;
        }
      }));

scanRouter.get("/:scanId", (async function (req, res, next) {
        try {
          var scanId = req.params["scanId"];
          var scanDoc = await db.scans.document(scanId);
          var violations = await Core.getViolationsForScan(db, scanId);
          res.json({
                success: true,
                data: {
                  scan: scanDoc,
                  violations: violations
                }
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

app.use("/v1/scan", scanRouter);

var violationsRouter = Express.default.Router();

violationsRouter.post("/", (async function (req, res, next) {
        try {
          var body = req.body;
          var url = Core__Option.flatMap(body["url"], Core__JSON.Decode.string);
          var violation = body["violation"];
          if (url === undefined) {
            return respondError(res, 400, "URL and violation are required");
          }
          if (violation === undefined) {
            return respondError(res, 400, "URL and violation are required");
          }
          var existing = await Core.getSiteByUrl(db, url);
          var siteKey;
          if (existing !== undefined) {
            siteKey = existing._key;
          } else {
            var urlObj = new URL(url);
            siteKey = (await db.sites.save({
                    url: url,
                    domain: urlObj.hostname,
                    firstScanned: new Date(),
                    lastScanned: new Date(),
                    scanCount: 0,
                    currentScore: 0,
                    status: "active"
                  }))._key;
          }
          await db.violations.save({
                siteKey: siteKey,
                scanKey: "",
                violationData: violation,
                timestamp: new Date(),
                fixed: false
              });
          res.json({
                success: true,
                message: "Violation reported successfully"
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

violationsRouter.get("/common", (async function (req, res, next) {
        try {
          var limit = Core__Option.getOr(Core__Option.flatMap(req.query["limit"], (function (s) {
                      return Core__Int.fromString(s, undefined);
                    })), 10);
          var violations = await Core.getCommonViolations(db, limit);
          res.json({
                success: true,
                data: violations
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

violationsRouter.get("/site/:siteKey", (async function (req, res, next) {
        try {
          var siteKey = req.params["siteKey"];
          var fixed = req.query["fixed"] === "true";
          var cursor = await db.violations.byExample({
                siteKey: siteKey,
                fixed: fixed
              });
          var violations = await cursor.all();
          res.json({
                success: true,
                data: violations
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

violationsRouter.patch("/:violationId/fixed", (async function (req, res, next) {
        try {
          var violationId = req.params["violationId"];
          await db.violations.update(violationId, {
                fixed: true
              });
          res.json({
                success: true,
                message: "Violation marked as fixed"
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

app.use("/v1/violations", violationsRouter);

var leaderboardRouter = Express.default.Router();

leaderboardRouter.get("/", (async function (req, res, next) {
        try {
          var limit = Core__Option.getOr(Core__Option.flatMap(req.query["limit"], (function (s) {
                      return Core__Int.fromString(s, undefined);
                    })), 100);
          var sites = await Core.getTopSites(db, limit);
          var leaderboard = sites.map(function (site, i) {
                var prev = site.previousScore;
                var trend = prev !== undefined ? site.currentScore - prev | 0 : 0;
                return {
                        rank: i + 1 | 0,
                        domain: site.domain,
                        url: site.url,
                        score: site.currentScore,
                        violations: site.scanCount,
                        lastScanned: site.lastScanned,
                        trend: trend
                      };
              });
          res.json({
                success: true,
                data: {
                  sites: leaderboard,
                  total: leaderboard.length,
                  lastUpdated: nowIso()
                }
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

leaderboardRouter.get("/category/:category", (async function (req, res, next) {
        try {
          var category = req.params["category"];
          var limit = Core__Option.getOr(Core__Option.flatMap(req.query["limit"], (function (s) {
                      return Core__Int.fromString(s, undefined);
                    })), 100);
          var sites = await Core.getTopSites(db, limit);
          res.json({
                success: true,
                data: {
                  category: category,
                  sites: sites,
                  total: sites.length
                }
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

app.use("/v1/leaderboard", leaderboardRouter);

var badgeRouter = Express.default.Router();

function getGrade(score) {
  if (score >= 90) {
    return "A";
  } else if (score >= 80) {
    return "B";
  } else if (score >= 70) {
    return "C";
  } else if (score >= 60) {
    return "D";
  } else {
    return "F";
  }
}

function gradeColor(grade) {
  switch (grade) {
    case "A" :
        return "#28a745";
    case "B" :
        return "#8bc34a";
    case "C" :
        return "#ffc107";
    case "D" :
        return "#ff9800";
    default:
      return "#dc3545";
  }
}

function generateBadgeSVG(score) {
  var grade = getGrade(score);
  var color = gradeColor(grade);
  var scoreStr = score.toString();
  return ("\n    <svg xmlns=\"https://www.w3.org/2000/svg\" width=\"160\" height=\"28\" role=\"img\" aria-label=\"Accessibility: " + grade + "\">\n      <title>Accessibility Score: " + scoreStr + " (Grade " + grade + ")</title>\n      <linearGradient id=\"s\" x2=\"0\" y2=\"100%\">\n        <stop offset=\"0\" stop-color=\"#bbb\" stop-opacity=\".1\"/>\n        <stop offset=\"1\" stop-opacity=\".1\"/>\n      </linearGradient>\n      <clipPath id=\"r\">\n        <rect width=\"160\" height=\"28\" rx=\"3\" fill=\"#fff\"/>\n      </clipPath>\n      <g clip-path=\"url(#r)\">\n        <rect width=\"100\" height=\"28\" fill=\"#555\"/>\n        <rect x=\"100\" width=\"60\" height=\"28\" fill=\"" + color + "\"/>\n        <rect width=\"160\" height=\"28\" fill=\"url(#s)\"/>\n      </g>\n      <g fill=\"#fff\" text-anchor=\"middle\" font-family=\"Verdana,Geneva,DejaVu Sans,sans-serif\" text-rendering=\"geometricPrecision\" font-size=\"11\">\n        <text aria-hidden=\"true\" x=\"50\" y=\"17.5\" fill=\"#010101\" fill-opacity=\".3\">accessibility</text>\n        <text x=\"50\" y=\"16.5\" fill=\"#fff\">accessibility</text>\n        <text aria-hidden=\"true\" x=\"130\" y=\"17.5\" fill=\"#010101\" fill-opacity=\".3\">" + grade + " (" + scoreStr + ")</text>\n        <text x=\"130\" y=\"16.5\" fill=\"#fff\">" + grade + " (" + scoreStr + ")</text>\n      </g>\n    </svg>\n  ").trim();
}

badgeRouter.get("/:domain", (async function (req, res, next) {
        try {
          var domain = req.params["domain"];
          var format = Core__Option.getOr(req.query["format"], "json");
          var cursor = await db.sites.byExample({
                domain: domain
              });
          var sites = await cursor.all();
          if (sites.length === 0) {
            return respondError(res, 404, "Site not found");
          }
          var site = sites[0];
          if (format === "svg") {
            var svg = generateBadgeSVG(site.currentScore);
            res.setHeader("Content-Type", "image/svg+xml");
            res.setHeader("Cache-Control", "public, max-age=3600");
            res.send(svg);
            return ;
          }
          var host = req.get("host");
          var proto = req.protocol;
          res.json({
                success: true,
                data: {
                  domain: domain,
                  score: site.currentScore,
                  grade: getGrade(site.currentScore),
                  lastScanned: site.lastScanned,
                  badgeUrl: proto + "://" + host + "/v1/badge/" + domain + "?format=svg"
                }
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

app.use("/v1/badge", badgeRouter);

var statsRouter = Express.default.Router();

statsRouter.get("/", (async function (_req, res, next) {
        try {
          var sitesCount = await db.sites.count();
          var scansCount = await db.scans.count();
          var violationsCount = await db.violations.count();
          var commonViolations = await Core.getCommonViolations(db, 5);
          res.json({
                success: true,
                data: {
                  totalSites: sitesCount.count,
                  totalScans: scansCount.count,
                  totalViolations: violationsCount.count,
                  commonViolations: commonViolations,
                  timestamp: nowIso()
                }
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

statsRouter.get("/site/:siteKey", (async function (req, res, next) {
        try {
          var siteKey = req.params["siteKey"];
          var site = await db.sites.document(siteKey);
          var scans = await Core.getRecentScansForSite(db, siteKey, 30);
          var trend = await Core.getSiteViolationTrend(db, siteKey, 30);
          res.json({
                success: true,
                data: {
                  site: site,
                  recentScans: scans,
                  trend: trend
                }
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

app.use("/v1/stats", statsRouter);

var dashboardRouter = Express.default.Router();

dashboardRouter.get("/:orgId", (async function (req, res, next) {
        try {
          var orgId = req.params["orgId"];
          var org = await db.organizations.document(orgId);
          var sites = await Core.getOrganizationSites(db, orgId);
          var totalSites = sites.length;
          var averageScore;
          if (totalSites > 0) {
            var sum = Core__Array.reduce(sites, 0, (function (acc, site) {
                    return acc + site.currentScore | 0;
                  }));
            averageScore = Caml_int32.div(sum, totalSites);
          } else {
            averageScore = 0;
          }
          var totalViolations = 0;
          for(var i = 0 ,i_finish = sites.length; i < i_finish; ++i){
            var site = sites[i];
            var cursor = await db.violations.byExample({
                  siteKey: site._key,
                  fixed: false
                });
            var count = Core__Option.getOr(cursor.count, 0);
            totalViolations = totalViolations + count | 0;
          }
          var siteSummaries = sites.map(function (site) {
                return {
                        domain: site.domain,
                        url: site.url,
                        score: site.currentScore,
                        lastScanned: site.lastScanned
                      };
              });
          res.json({
                success: true,
                data: {
                  organization: {
                    name: org.name,
                    tier: org.tier
                  },
                  stats: {
                    totalSites: totalSites,
                    averageScore: averageScore,
                    totalViolations: totalViolations
                  },
                  sites: siteSummaries
                }
              });
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            next(err._1);
            return ;
          }
          throw err;
        }
      }));

app.use("/v1/dashboard", dashboardRouter);

app.use(function (err, _req, res, _next) {
      console.error("Error:", err);
      var message = Core__Option.getOr(err.message, "Internal server error");
      res.status(500);
      res.json({
            error: {
              message: message,
              status: 500
            }
          });
    });

app.use(function (_req, res, _next) {
      res.status(404);
      res.json({
            error: {
              message: "Endpoint not found",
              status: 404
            }
          });
    });

async function startServer() {
  await initializeDatabase();
  app.listen(port, (function () {
          console.log("✓ Accessibility Everywhere API listening on port " + port.toString());
          var env = Core__Option.getOr(process.env.NODE_ENV, "development");
          console.log("✓ Environment: " + env);
          console.log("✓ Health check: http://localhost:" + port.toString() + "/health");
          console.log("✓ API docs: http://localhost:" + port.toString() + "/v1");
        }));
}

Core__Promise.$$catch(startServer(), (function (err) {
        console.error("Failed to start server:", err);
        return (process.exit(1));
      }));

export {
  db ,
  scanner ,
  app ,
  port ,
  nowIso ,
  nowDate ,
  limiter ,
  initializeDatabase ,
  respondError ,
  scanRouter ,
  scanSchema ,
  parseWcagLevel ,
  violationsRouter ,
  leaderboardRouter ,
  badgeRouter ,
  getGrade ,
  gradeColor ,
  generateBadgeSVG ,
  statsRouter ,
  dashboardRouter ,
  startServer ,
}
/*  Not a pure module */
